### ISSUE TITLE
Software crashes after running DrupalPro14 scripts

### ISSUE THREAD

**Issue by UTANdev** [jcmartinez/drupalpro14#4]
Having to replace my rapidly-dying old Quickstart environment, I was enthused to see that a fork of DrupalPro was still actively maintained. Unfortunately, my fresh Ubuntu 14.04.3 64-bit install in VirtualBox (Win7 host) started acting flaky once I ran the DP14 install scripts. (I ran run_all.sh) It was fine before I installed DP14. Software keeps crashing, like the Unity control center which crashed with this dialog:
[crash report](http://i.imgur.com/XjmrhEI.png)
Any suggestions? Thanks.

**Comment by jcmartinez** [comment]
Hi, I haven't seen this issue with any of my installations. You mentioned your aging old Quickstart environment. Could it be a problem with the underliying Virtual computer or the physical computer?

Did you install the Virtualbox guest additions?

Could you try a different distribution of Ubuntu or a different machine? I've been running a Linux mint  gust first on Windows 7 now on a Windows 10 host every day for months with no issue. It should work in most distros anyway.

Unity uses more memory than other environments. Are you sure there is enough memory?

**Comment by UTANdev** [comment]
My physical PC is fine; it came back from a refresh at the shop this fall. Quickstart wouldn't be the problem, since I'm installing DrupalPro14 on a new VM. I had given the VM 2GB of memory and a 15GB virtual disk. I'll try installing Linux Mint instead of Ubuntu in a new VM, give it 3GB, and report back.

**Comment by UTANdev** [comment]
D'oh — I didn't notice that, since I was installing on Linux Mint rather than Ubuntu, I had to use the selective install and skip the cleanup 1-cleanup.sh script.

At first glance, everything now seems to work well. Thanks, JC!
